name: GoldTouch
version: 1.0.0
main: lad.obsidian.goldtouch.GoldTouch
author: Obsidianlad
description: Silk Touch for gold tools

permissions:
  goldtouch.use:
    default: true
    description: Is able to use GoldTouch.
